import type { Scenario, PlaybackFrame, MetricsSnapshot } from "./types";

export const SCENARIOS: Scenario[] = [
  {
    id: "authorized_staff",
    title: "Authorized Staff Entry",
    subtitle: "Standard access granted",
    description: "A registered employee with valid credentials approaches the gate. All biometric and vehicle checks pass within normal thresholds.",
    outcome: "granted",
    severity: "safe",
    icon: "CheckCircle",
    duration: 8000,
    steps: [
      { id: "approach", label: "Vehicle Approaches", narration: "Registered vehicle ABC-123XY approaching Gate A at 8 km/h. Camera 01 tracking.", duration: 800, status: "success" },
      { id: "capture", label: "Plate Capture", narration: "License plate captured: ABC-123XY. Region of interest isolated.", duration: 600, status: "success", confidence: 99.7 },
      { id: "ocr", label: "OCR Processing", narration: "OCR engine reading plate: A-B-C-1-2-3-X-Y. Character confidence: 99.1%.", duration: 700, status: "success", confidence: 99.1 },
      { id: "face", label: "Face Recognition", narration: "Driver face matched to registered profile: John Doe (Employee ID: EMP-4421). Liveness verified.", duration: 1000, status: "success", confidence: 98.9 },
      { id: "vehicle", label: "Vehicle Verification", narration: "Vehicle fingerprint matches registered Toyota Camry 2024 (Silver).", duration: 800, status: "success", confidence: 97.3 },
      { id: "policy", label: "Policy Check", narration: "Access policy 'Standard Hours' grants entry 06:00-22:00. Current time: 09:15. Allowed.", duration: 600, status: "success" },
      { id: "decision", label: "Decision Engine", narration: "All checks passed. Verdict: ACCESS GRANTED. Gate opening sequence initiated.", duration: 1000, status: "success", confidence: 99.8 },
      { id: "gate", label: "Gate Opens", narration: "Gate A barrier raised in 2.1s. Vehicle entering. Session #88421 started.", duration: 800, status: "success" },
    ],
    evidence: [
      { type: "camera", label: "Gate Camera Feed", value: "Vehicle ABC-123XY approaching at 08:14:23", confidence: 99.7, status: "match" },
      { type: "plate", label: "License Plate", value: "ABC-123XY (Registered)", confidence: 99.1, status: "match" },
      { type: "face", label: "Driver Face", value: "John Doe - EMP-4421", confidence: 98.9, status: "match" },
      { type: "vehicle", label: "Vehicle Profile", value: "Toyota Camry 2024 - Silver", confidence: 97.3, status: "match" },
      { type: "identity", label: "Identity Record", value: "Active Employee - Access Level 3", confidence: 100, status: "match" },
      { type: "policy", label: "Access Policy", value: "Standard Hours - Entry Allowed", confidence: 100, status: "match" },
    ],
    reasoning: [
      { step: "Plate Recognition", detail: "OCR matched ABC-123XY with 99.1% confidence against registered plates", result: "PASS", passed: true },
      { step: "Face Matching", detail: "Face embedding cosine similarity 0.94 against John Doe (threshold: 0.65)", result: "PASS", passed: true },
      { step: "Vehicle Fingerprint", detail: "Make/model/color profile match 97.3% against registered vehicle", result: "PASS", passed: true },
      { step: "Policy Evaluation", detail: "Access policy 'Standard Hours' active. Time window: 06:00-22:00.", result: "PASS", passed: true },
      { step: "Risk Assessment", detail: "Anomaly score: 0.02 (threshold: 0.70). No behavioral flags.", result: "PASS", passed: true },
      { step: "Final Verdict", detail: "All 5 checks passed. Confidence weighted average: 99.1%", result: "ACCESS GRANTED", passed: true },
    ],
  },
  {
    id: "unauthorized_visitor",
    title: "Unauthorized Visitor",
    subtitle: "Identity not recognized",
    description: "An unregistered vehicle with an unknown driver attempts to enter. The system denies access and alerts security.",
    outcome: "denied",
    severity: "warning",
    icon: "ShieldX",
    duration: 7000,
    steps: [
      { id: "approach", label: "Vehicle Approaches", narration: "Unknown vehicle approaching Gate B. No RFID tag detected.", duration: 800, status: "success" },
      { id: "capture", label: "Plate Capture", narration: "Plate captured: XYZ-789. Querying registered vehicles...", duration: 600, status: "success", confidence: 98.2 },
      { id: "ocr", label: "OCR Processing", narration: "OCR result: X-Y-Z-7-8-9. Not found in registered vehicle database.", duration: 700, status: "warning", confidence: 98.2 },
      { id: "face", label: "Face Recognition", narration: "Driver face captured. No match found across 15,200 registered identities.", duration: 1000, status: "fail", confidence: 12.4 },
      { id: "vehicle", label: "Vehicle Check", narration: "Vehicle not registered in system. VIN query returned no matching records.", duration: 800, status: "fail" },
      { id: "policy", label: "Policy Evaluation", narration: "No identity record found. Default policy: DENY for unregistered entities.", duration: 600, status: "warning" },
      { id: "decision", label: "Decision Engine", narration: "Zero identity matches. Verdict: ACCESS DENIED. Security alert dispatched.", duration: 1000, status: "fail", confidence: 12.4 },
      { id: "gate", label: "Gate Remains Closed", narration: "Gate B remains locked. Security personnel notified. Incident #88422 logged.", duration: 800, status: "warning" },
    ],
    evidence: [
      { type: "camera", label: "Gate Camera Feed", value: "Unknown vehicle at Gate B - 08:15:01", confidence: 98.2, status: "match" },
      { type: "plate", label: "License Plate", value: "XYZ-789 (Not Registered)", confidence: 98.2, status: "not_found" },
      { type: "face", label: "Driver Face", value: "No Match - Unknown Identity", confidence: 12.4, status: "not_found" },
      { type: "vehicle", label: "Vehicle Profile", value: "Unregistered - No VIN Match", confidence: 0, status: "not_found" },
      { type: "identity", label: "Identity Record", value: "No Record Found", confidence: 0, status: "not_found" },
      { type: "policy", label: "Access Policy", value: "Default Deny - Unknown Entity", confidence: 100, status: "match" },
    ],
    reasoning: [
      { step: "Plate Recognition", detail: "OCR matched XYZ-789 with 98.2% confidence. Not found in registry.", result: "NOT FOUND", passed: false },
      { step: "Face Matching", detail: "Face embedding compared against 15,200 profiles. Max similarity: 0.08.", result: "NO MATCH", passed: false },
      { step: "Vehicle Fingerprint", detail: "No VIN match in registered vehicle database (0 records).", result: "NOT FOUND", passed: false },
      { step: "Policy Evaluation", detail: "Default deny policy for unregistered entities (Policy ID: DEFAULT-001).", result: "DENY", passed: false },
      { step: "Risk Assessment", detail: "Anomaly score: 0.85. Unknown entity at restricted facility.", result: "HIGH RISK", passed: false },
      { step: "Final Verdict", detail: "0 of 4 checks passed. Identity unknown. Access prohibited.", result: "ACCESS DENIED", passed: false },
    ],
  },
  {
    id: "vehicle_mismatch",
    title: "Vehicle Mismatch",
    subtitle: "Plate does not match vehicle",
    description: "The license plate belongs to a registered vehicle, but the physical vehicle detected does not match the registered make/model.",
    outcome: "denied",
    severity: "warning",
    icon: "Truck",
    duration: 7500,
    steps: [
      { id: "approach", label: "Vehicle Approaches", narration: "Vehicle approaching Gate A. Plate detected: ABC-123XY.", duration: 800, status: "success" },
      { id: "ocr", label: "Plate Recognized", narration: "Plate ABC-123XY recognized. Associated with registered Toyota Camry.", duration: 600, status: "success", confidence: 99.3 },
      { id: "face", label: "Face Match", narration: "Driver John Doe matches registered profile for this plate.", duration: 900, status: "success", confidence: 98.7 },
      { id: "vehicle", label: "Vehicle Mismatch Detected", narration: "WARNING: Detected vehicle is a Honda Accord, NOT the registered Toyota Camry. Visual fingerprint mismatch.", duration: 1200, status: "fail", confidence: 23.1 },
      { id: "policy", label: "Policy Evaluation", narration: "Vehicle mismatch policy: FLAG for manual review. Possible plate theft or cloning.", duration: 700, status: "warning" },
      { id: "decision", label: "Decision Engine", narration: "Driver matched but vehicle mismatched. Verdict: ACCESS DENIED. Escalating to security.", duration: 1000, status: "fail", confidence: 23.1 },
      { id: "gate", label: "Gate Remains Closed", narration: "Gate A locked. Security dispatched. Evidence package created.", duration: 800, status: "warning" },
    ],
    evidence: [
      { type: "plate", label: "License Plate", value: "ABC-123XY (Registered)", confidence: 99.3, status: "match" },
      { type: "face", label: "Driver Face", value: "John Doe - EMP-4421", confidence: 98.7, status: "match" },
      { type: "vehicle", label: "Detected Vehicle", value: "Honda Accord 2023 - Black", confidence: 23.1, status: "mismatch" },
      { type: "identity", label: "Registered Vehicle", value: "Toyota Camry 2024 - Silver", confidence: 0, status: "mismatch" },
      { type: "policy", label: "Access Policy", value: "Vehicle Verification Required", confidence: 100, status: "match" },
    ],
    reasoning: [
      { step: "Plate Recognition", detail: "Plate ABC-123XY matched to registered vehicle (Toyota Camry).", result: "PASS", passed: true },
      { step: "Face Matching", detail: "Driver John Doe authorized for this plate.", result: "PASS", passed: true },
      { step: "Vehicle Fingerprint", detail: "Detected: Honda Accord. Expected: Toyota Camry. Model mismatch.", result: "FAIL", passed: false },
      { step: "Policy Evaluation", detail: "Policy VC-002: Vehicle must match registered profile. Flag on mismatch.", result: "FLAG", passed: false },
      { step: "Risk Assessment", detail: "Anomaly score: 0.92. Possible plate cloning/theft.", result: "HIGH RISK", passed: false },
      { step: "Final Verdict", detail: "Face match but vehicle mismatch. 2/5 checks failed.", result: "DENIED", passed: false },
    ],
  },
  {
    id: "face_mismatch",
    title: "Face Mismatch",
    subtitle: "Driver face does not match",
    description: "The license plate and vehicle are registered, but the driver's face does not match the authorized profile.",
    outcome: "denied",
    severity: "critical",
    icon: "UserX",
    duration: 7500,
    steps: [
      { id: "approach", label: "Vehicle Approaches", narration: "Vehicle ABC-123XY approaching. Plate and vehicle appear registered.", duration: 800, status: "success" },
      { id: "ocr", label: "Plate Recognized", narration: "Plate ABC-123XY registered to John Doe, Toyota Camry.", duration: 600, status: "success", confidence: 99.5 },
      { id: "vehicle", label: "Vehicle Verified", narration: "Toyota Camry 2024 Silver matches registered profile.", duration: 700, status: "success", confidence: 97.8 },
      { id: "face", label: "Face Mismatch Detected", narration: "ALERT: Driver face does NOT match John Doe. Face similarity: 23.4% (threshold: 65%).", duration: 1200, status: "fail", confidence: 23.4 },
      { id: "policy", label: "Policy Evaluation", narration: "Face mismatch on registered vehicle. Possible identity fraud. Policy: DENY + Security alert.", duration: 700, status: "warning" },
      { id: "decision", label: "Decision Engine", narration: "Vehicle valid but driver mismatch. Verdict: ACCESS DENIED. Security dispatched to Gate A.", duration: 1000, status: "fail", confidence: 23.4 },
      { id: "gate", label: "Gate Locked", narration: "Gate A secured. Unauthorized driver attempt logged. Police notified.", duration: 800, status: "critical" },
    ],
    evidence: [
      { type: "plate", label: "License Plate", value: "ABC-123XY (Verified)", confidence: 99.5, status: "match" },
      { type: "vehicle", label: "Vehicle", value: "Toyota Camry 2024 - Silver", confidence: 97.8, status: "match" },
      { type: "face", label: "Driver Face", value: "Unknown - Not John Doe", confidence: 23.4, status: "mismatch" },
      { type: "identity", label: "Expected Driver", value: "John Doe - EMP-4421", confidence: 100, status: "mismatch" },
    ],
    reasoning: [
      { step: "Plate Recognition", detail: "Plate ABC-123XY verified as registered.", result: "PASS", passed: true },
      { step: "Vehicle Fingerprint", detail: "Vehicle match confirmed (Toyota Camry).", result: "PASS", passed: true },
      { step: "Face Matching", detail: "Face similarity 0.234. Below threshold 0.65. Identity fraud suspected.", result: "FAIL", passed: false },
      { step: "Policy Evaluation", detail: "Policy ID-002: Driver biometric must match registered profile.", result: "DENY", passed: false },
      { step: "Risk Assessment", detail: "Anomaly score: 0.96. Vehicle/person mismatch - likely theft.", result: "CRITICAL", passed: false },
      { step: "Final Verdict", detail: "Vehicle OK but driver UNKNOWN. 2/5 checks failed.", result: "DENIED + ALERT", passed: false },
    ],
  },
  {
    id: "expired_permit",
    title: "Expired Permit",
    subtitle: "Access permit has expired",
    description: "A registered driver's access permit has expired. The system denies entry until renewal is processed.",
    outcome: "denied",
    severity: "warning",
    icon: "Clock",
    duration: 7000,
    steps: [
      { id: "approach", label: "Vehicle Approaches", narration: "Registered vehicle approaching. Driver known to system.", duration: 800, status: "success" },
      { id: "ocr", label: "Identity Found", narration: "Plate ABC-123XY, driver Jane Smith, EMP-5592 found.", duration: 600, status: "success", confidence: 99.2 },
      { id: "face", label: "Face Verified", narration: "Face match confirmed: Jane Smith (98.7% confidence).", duration: 900, status: "success", confidence: 98.7 },
      { id: "vehicle", label: "Vehicle Verified", narration: "Vehicle match confirmed. All biometrics pass.", duration: 700, status: "success", confidence: 97.1 },
      { id: "policy", label: "Permit Expired", narration: "NOTICE: Access permit for Jane Smith expired 2026-06-30 (15 days ago). Renewal required.", duration: 1000, status: "fail", confidence: 100 },
      { id: "decision", label: "Decision Engine", narration: "Identity verified but permit expired. Verdict: ACCESS DENIED. Notification sent to HR.", duration: 1000, status: "fail", confidence: 100 },
      { id: "gate", label: "Gate Remains Closed", narration: "Gate A closed. Driver advised to contact HR for permit renewal.", duration: 800, status: "warning" },
    ],
    evidence: [
      { type: "plate", label: "License Plate", value: "ABC-123XY", confidence: 99.2, status: "match" },
      { type: "face", label: "Driver Face", value: "Jane Smith - EMP-5592", confidence: 98.7, status: "match" },
      { type: "vehicle", label: "Vehicle", value: "Honda Civic 2023 (Registered)", confidence: 97.1, status: "match" },
      { type: "identity", label: "Permit Status", value: "Expired - 15 days overdue", confidence: 100, status: "expired" },
      { type: "policy", label: "Access Policy", value: "Valid permit required for entry", confidence: 100, status: "match" },
    ],
    reasoning: [
      { step: "Identity Verification", detail: "Jane Smith identified (EMP-5592).", result: "PASS", passed: true },
      { step: "Face Matching", detail: "Face match confidence 98.7%. Liveness confirmed.", result: "PASS", passed: true },
      { step: "Vehicle Check", detail: "Honda Civic 2023 registered to Jane Smith.", result: "PASS", passed: true },
      { step: "Permit Validation", detail: "Permit #PRM-4421 expired 2026-06-30. Status: INACTIVE.", result: "EXPIRED", passed: false },
      { step: "Policy Evaluation", detail: "Policy EXP-001: Active permit required. Renewal grace period: 0 days post-expiry.", result: "DENY", passed: false },
      { step: "Final Verdict", detail: "Identity valid but permit inactive. Renewal required.", result: "DENIED", passed: false },
    ],
  },
  {
    id: "emergency_override",
    title: "Emergency Override",
    subtitle: "Manual gate override activated",
    description: "Security personnel manually override the gate during an emergency situation, bypassing all automated checks.",
    outcome: "override",
    severity: "critical",
    icon: "AlertTriangle",
    duration: 5000,
    steps: [
      { id: "alert", label: "Emergency Alert", narration: "ALERT: Fire alarm triggered in Building B. Emergency protocols activated.", duration: 1000, status: "warning" },
      { id: "override", label: "Override Initiated", narration: "Security officer dispatches emergency override for all gates. Automated checks bypassed.", duration: 800, status: "success" },
      { id: "gate", label: "All Gates Opening", narration: "Emergency mode: All 4 gates opening. Barriers raised. Priority: evacuation.", duration: 1000, status: "warning" },
      { id: "vehicles", label: "Evacuation Flow", narration: "12 vehicles exiting via Gates A-D. Emergency lane activated.", duration: 800, status: "success" },
      { id: "log", label: "Incident Logged", narration: "Emergency override logged. Incident #EM-2026-07-15-001 created for audit.", duration: 600, status: "success" },
      { id: "reset", label: "System Reset", narration: "Emergency protocols complete. Gates returning to automated operation. Post-incident review scheduled.", duration: 800, status: "success" },
    ],
    evidence: [
      { type: "camera", label: "Security Camera", value: "Building B - Smoke detected at 08:16:45", confidence: 99.9, status: "match" },
      { type: "policy", label: "Emergency Protocol", value: "Emergency Override - All Gates Open", confidence: 100, status: "match" },
      { type: "identity", label: "Authorizing Officer", value: "Lt. Maria Rodriguez - Badge #884", confidence: 100, status: "match" },
    ],
    reasoning: [
      { step: "Event Detection", detail: "Fire alarm system triggered (Zone B-3). Automated emergency sequence.", result: "CONFIRMED", passed: true },
      { step: "Override Authorization", detail: "Lt. Rodriguez (Badge #884) authorized emergency override.", result: "AUTHORIZED", passed: true },
      { step: "Gate Control", detail: "Emergency mode: All gates set to OPEN. Barriers raised.", result: "OPEN", passed: true },
      { step: "Safety Check", detail: "Evacuation routes clear. Emergency lane operational.", result: "SAFE", passed: true },
      { step: "Final Verdict", detail: "Emergency override executed. Post-incident review required within 24h.", result: "OVERRIDE", passed: true },
    ],
  },
  {
    id: "manual_review",
    title: "Manual Review Required",
    subtitle: "Ambiguous match sent to human",
    description: "The AI system encounters a low-confidence match and escalates the decision to a human security operator for review.",
    outcome: "review",
    severity: "warning",
    icon: "Eye",
    duration: 8000,
    steps: [
      { id: "approach", label: "Vehicle Approaches", narration: "Vehicle approaching Gate C. Standard capture sequence initiated.", duration: 800, status: "success" },
      { id: "ocr", label: "Plate Partially Matched", narration: "Plate detected: ABC-12. Partial match only. Mud/damage on plate region.", duration: 700, status: "warning", confidence: 72.4 },
      { id: "face", label: "Face - Low Confidence", narration: "Face captured but sunglasses obscure key features. Confidence: 68.2%", duration: 900, status: "warning", confidence: 68.2 },
      { id: "vehicle", label: "Vehicle - Inconclusive", narration: "Aftermarket modifications detected. Visual fingerprint only 61.3% match.", duration: 800, status: "warning", confidence: 61.3 },
      { id: "decision", label: "Escalating to Human", narration: "AI confidence below 75% threshold. Decision routed to manual review queue.", duration: 1000, status: "warning", confidence: 67.3 },
      { id: "review", label: "Human Review", narration: "Security Officer reviewing case #MR-4421. Cross-referencing database...", duration: 1500, status: "running" },
      { id: "approved", label: "Review Approved", narration: "Officer confirmed identity. Manual override granted. Gate opening.", duration: 1000, status: "success", confidence: 95 },
      { id: "gate", label: "Gate Opens", narration: "Gate C opened via manual review. Audit trail updated with officer notes.", duration: 800, status: "success" },
    ],
    evidence: [
      { type: "plate", label: "Plate (Partial)", value: "ABC-12** (Partial - 72.4%)", confidence: 72.4, status: "match" },
      { type: "face", label: "Driver Face", value: "John *** (Partial - 68.2%)", confidence: 68.2, status: "mismatch" },
      { type: "vehicle", label: "Modified Vehicle", value: "Toyota *** (Modified - 61.3%)", confidence: 61.3, status: "mismatch" },
      { type: "identity", label: "Likely Match", value: "John Davis - EMP-7712 (Manual review)", confidence: 95, status: "match" },
    ],
    reasoning: [
      { step: "Plate Recognition", detail: "Partial plate match (72.4%). Plate damage detected.", result: "LOW CONFIDENCE", passed: true },
      { step: "Face Matching", detail: "Occlusion from eyewear. Confidence below threshold.", result: "LOW CONFIDENCE", passed: true },
      { step: "Vehicle Check", detail: "Aftermarket modifications reduce fingerprint reliability.", result: "LOW CONFIDENCE", passed: true },
      { step: "AI Confidence", detail: "Weighted confidence 67.3% below 75% auto-decision threshold.", result: "ESCALATE", passed: false },
      { step: "Human Review", detail: "Officer reviewed evidence: plate, face, vehicle, history. Match confirmed.", result: "APPROVED", passed: true },
      { step: "Final Verdict", detail: "Human-in-the-loop decision. Manual override approved.", result: "GRANTED (MANUAL)", passed: true },
    ],
  },
  {
    id: "vip_entry",
    title: "VIP / Executive Entry",
    subtitle: "Priority access with enhanced service",
    description: "A VIP executive arrives. Priority lane opened, escort notified, and concierge service activated.",
    outcome: "granted",
    severity: "safe",
    icon: "Star",
    duration: 7000,
    steps: [
      { id: "approach", label: "VIP Vehicle Detected", narration: "VIP vehicle approaching Priority Lane 1. RFID tag: VIP-0001 detected.", duration: 800, status: "success" },
      { id: "capture", label: "Identity Confirmed", narration: "CEO Sarah Chen identified. Face match 99.8%. Executive priority profile.", duration: 700, status: "success", confidence: 99.8 },
      { id: "plate", label: "Plate Recognized", narration: "Plate: VIP-0001K. Executive fleet vehicle - pre-cleared.", duration: 500, status: "success", confidence: 99.9 },
      { id: "policy", label: "VIP Policy Activated", narration: "VIP protocol: Priority lane, escort standby, concierge notified.", duration: 600, status: "success" },
      { id: "decision", label: "Instant Approval", narration: "VIP profile pre-approved. Skip all standard checks. Priority override.", duration: 600, status: "success", confidence: 100 },
      { id: "gate", label: "Priority Lane Open", narration: "Priority Gate 1 opening with green indicator. Security escort awaiting.", duration: 800, status: "success" },
      { id: "notify", label: "Concierge Notified", narration: "Executive assistant notified. Reserved parking spot #A1 prepared.", duration: 600, status: "success" },
    ],
    evidence: [
      { type: "camera", label: "Priority Lane", value: "VIP vehicle at Priority Gate - 08:17:00", confidence: 100, status: "match" },
      { type: "plate", label: "VIP Plate", value: "VIP-001K (Executive Fleet)", confidence: 99.9, status: "match" },
      { type: "face", label: "Driver Face", value: "Sarah Chen - CEO", confidence: 99.8, status: "match" },
      { type: "identity", label: "VIP Profile", value: "Executive Priority - Level 5 Access", confidence: 100, status: "match" },
      { type: "policy", label: "VIP Protocol", value: "Priority Processing - Escort Ready", confidence: 100, status: "match" },
    ],
    reasoning: [
      { step: "RFID Detection", detail: "VIP RFID tag (VIP-0001) detected at priority lane.", result: "PASS", passed: true },
      { step: "Face Matching", detail: "CEO Sarah Chen confirmed. VIP profile priority override.", result: "PASS", passed: true },
      { step: "Policy Evaluation", detail: "VIP policy: Express processing, no standard checks required.", result: "VIP OVERRIDE", passed: true },
      { step: "Concierge", detail: "Escort team and concierge notified via VIP channel.", result: "NOTIFIED", passed: true },
      { step: "Final Verdict", detail: "VIP priority protocol executed. 100% confidence.", result: "GRANTED (VIP)", passed: true },
    ],
  },
  {
    id: "stolen_vehicle",
    title: "Stolen Vehicle Detection",
    subtitle: "Flagged vehicle intercepted",
    description: "A vehicle reported stolen is detected by the system. Security and law enforcement are automatically dispatched.",
    outcome: "denied",
    severity: "critical",
    icon: "Siren",
    duration: 8000,
    steps: [
      { id: "approach", label: "Vehicle Approaches", narration: "Vehicle approaching Gate D. Standard capture initiated.", duration: 800, status: "success" },
      { id: "plate", label: "Plate Detected", narration: "Plate: HIJ-456. Querying databases...", duration: 600, status: "success", confidence: 99.4 },
      { id: "check", label: "STOLEN VEHICLE ALERT", narration: "ALERT: Vehicle HIJ-456 reported stolen 2026-07-12. Wanted in connection with theft.", duration: 1500, status: "critical", confidence: 100 },
      { id: "protocol", label: "Containment Protocol", narration: "Lockdown protocol activated. All gates securing. Barrier spike strip armed.", duration: 1000, status: "critical" },
      { id: "notify", label: "Authorities Notified", narration: "Security dispatched to Gate D. Police notified. Suspect vehicle contained.", duration: 800, status: "critical" },
      { id: "decision", label: "Decision Engine", narration: "Stolen vehicle match confirmed. Verdict: DETAIN + POLICE. Gate locked.", duration: 1000, status: "critical" },
      { id: "gate", label: "Gate Secured", narration: "Gate D in lockdown. Vehicle unable to exit. Police ETA: 4 minutes.", duration: 800, status: "critical" },
    ],
    evidence: [
      { type: "plate", label: "License Plate", value: "HIJ-456 (Stolen Vehicle)", confidence: 99.4, status: "match" },
      { type: "camera", label: "Gate Camera", value: "Suspect vehicle contained at Gate D", confidence: 100, status: "match" },
      { type: "identity", label: "Police Database", value: "Stolen Vehicle Report #LPD-2026-771", confidence: 100, status: "match" },
      { type: "vehicle", label: "Visual Confirmation", value: "Black Honda Accord - Matches stolen vehicle description", confidence: 97.2, status: "match" },
    ],
    reasoning: [
      { step: "Plate Query", detail: "HIJ-456 found in National Stolen Vehicle Database. Reported 2026-07-12.", result: "STOLEN", passed: false },
      { step: "Visual Confirmation", detail: "Black Honda Accord matches stolen vehicle description.", result: "MATCH", passed: true },
      { step: "Risk Assessment", detail: "Anomaly score: 1.00 (MAX). Stolen vehicle with possible armed suspect.", result: "CRITICAL", passed: false },
      { step: "Containment", detail: "Lockdown protocol initiated. Spike strip armed. Exit blocked.", result: "CONTAINED", passed: true },
      { step: "Law Enforcement", detail: "Police dispatched. LPD notified. Evidence package prepared.", result: "NOTIFIED", passed: true },
      { step: "Final Verdict", detail: "Stolen vehicle intercepted. Law enforcement response in progress.", result: "DETAINED", passed: false },
    ],
  },
  {
    id: "tailgating_attempt",
    title: "Tailgating Attempt",
    subtitle: "Unauthorized follow-through",
    description: "A vehicle attempts to follow an authorized vehicle through the gate before it closes. The system detects and prevents the breach.",
    outcome: "denied",
    severity: "critical",
    icon: "TriangleAlert",
    duration: 7500,
    steps: [
      { id: "entry", label: "Authorized Entry", narration: "Vehicle ABC-123XY authorized. Gate A opening for entry.", duration: 800, status: "success" },
      { id: "detect", label: "Second Vehicle Detected", narration: "ALERT: Second vehicle detected in gate zone while gate is open. Tailgating attempt suspected.", duration: 1000, status: "critical" },
      { id: "analysis", label: "Behavior Analysis", narration: "Vehicle 2 accelerating from 5m behind. Speed: 15 km/h. No valid credentials detected.", duration: 1000, status: "warning" },
      { id: "response", label: "Anti-Tailgating Response", narration: "Emergency gate reversal: Gate A closing immediately. Optical sensors triggered.", duration: 800, status: "critical" },
      { id: "capture", label: "Evidence Capture", narration: "Vehicle 2 plate captured: XYZ-999. Face capture: unknown male. Evidence package created.", duration: 1000, status: "warning", confidence: 88.3 },
      { id: "decision", label: "Decision Engine", narration: "Tailgating confirmed. Verdict: BREACH PREVENTED. Alerting security with vehicle details.", duration: 1000, status: "success", confidence: 99.9 },
      { id: "gate", label: "Gate Secured", narration: "Gate A closed. Vehicle 1 inside facility. Vehicle 2 outside. Security investigating.", duration: 800, status: "warning" },
    ],
    evidence: [
      { type: "camera", label: "Gate Camera 1", value: "Vehicle ABC-123XY entering (authorized)", confidence: 99.9, status: "match" },
      { type: "camera", label: "Gate Camera 2", value: "Vehicle XYZ-999 following at 0.8m (UNAUTHORIZED)", confidence: 99.9, status: "match" },
      { type: "plate", label: "Following Vehicle", value: "XYZ-999 (Not Registered)", confidence: 88.3, status: "not_found" },
      { type: "face", label: "Following Driver", value: "Unknown Male - No Match", confidence: 45.2, status: "not_found" },
    ],
    reasoning: [
      { step: "Gate State", detail: "Gate A open for authorized vehicle (ABC-123XY).", result: "OPEN", passed: true },
      { step: "Zone Monitoring", detail: "Optical sensors detect SECOND vehicle in safety zone.", result: "INTRUSION", passed: false },
      { step: "Behavior Analysis", detail: "Vehicle accelerated from 5m. Speed: 15 km/h. No RFID/credential.", result: "SUSPICIOUS", passed: false },
      { step: "Anti-Tailgating", detail: "Emergency reversal triggered. Gate closing in 0.4s.", result: "ACTIVATED", passed: true },
      { step: "Risk Assessment", detail: "Anomaly score: 0.94. Deliberate security breach attempt.", result: "HIGH RISK", passed: false },
      { step: "Final Verdict", detail: "Breach prevented. Vehicle 2 denied. Security dispatched.", result: "PREVENTED", passed: true },
    ],
  },
];

export const VIEW_CONFIG = {
  scenarios: { label: "Scenarios", icon: "List" },
  auto: { label: "Auto Demo", icon: "Play" },
  presentation: { label: "Presentation", icon: "Monitor" },
  judge: { label: "Judge Mode", icon: "Scale" },
  metrics: { label: "Live Metrics", icon: "BarChart3" },
  story: { label: "AI Story", icon: "Radio" },
  playback: { label: "Playback", icon: "Video" },
} as const;

export function generatePlaybackFrames(): PlaybackFrame[] {
  const frames: PlaybackFrame[] = [];
  const baseTime = Date.now() - 30000;
  for (let i = 0; i < 60; i++) {
    frames.push({
      id: `frame-${i}`,
      timestamp: new Date(baseTime + i * 500).toISOString(),
      camera: i % 3 === 0 ? "Camera 01" : i % 3 === 1 ? "Camera 02" : "Camera 03",
      label: i < 20 ? "Vehicle Approaching" : i < 35 ? "Plate Detection" : i < 45 ? "Face Recognition" : i < 55 ? "Decision Processing" : "Gate Operation",
      confidence: 85 + Math.random() * 15,
      imageUrl: "",
      type: i < 20 ? "capture" : i < 30 ? "plate" : i < 40 ? "face" : i < 50 ? "vehicle" : i < 55 ? "decision" : "gate",
    });
  }
  return frames;
}

export function generateMetricsHistory(): MetricsSnapshot[] {
  const snapshots: MetricsSnapshot[] = [];
  const baseTime = Date.now() - 3600000;
  for (let i = 0; i < 60; i++) {
    snapshots.push({
      entries: Math.floor(Math.random() * 8 + 2),
      exits: Math.floor(Math.random() * 6 + 1),
      denied: Math.floor(Math.random() * 2),
      manualReviews: Math.floor(Math.random() * 1),
      incidents: Math.floor(Math.random() * 1),
      avgProcessingTime: Math.floor(Math.random() * 800 + 400),
      throughput: Math.floor(Math.random() * 10 + 5),
      timestamp: new Date(baseTime + i * 60000).toISOString(),
    });
  }
  return snapshots;
}
