export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
  },
  HEALTH: "/health",
  USERS: {
    BASE: "/users",
    PROFILE: "/users/me",
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  SEARCH: "/search",
  CAMERA: {
    START: "/camera/start",
    STOP: "/camera/stop",
    STATUS: "/camera/status",
    CAPTURE: "/camera/capture",
  },
  PLATE_DETECTION: {
    DETECT_UPLOAD: "/plate-detection/detect/upload",
    DETECT_CAMERA: "/plate-detection/detect/camera",
    HISTORY: "/plate-detection/history",
  },
  OCR: {
    READ: "/ocr/read",
    HISTORY: "/ocr/history",
  },
  FACE: {
    RECOGNIZE_UPLOAD: "/face/recognize/upload",
    RECOGNIZE_CAMERA: "/face/recognize/camera",
    HISTORY: "/face/history",
  },
  VEHICLE: {
    FINGERPRINT_UPLOAD: "/vehicle/fingerprint/upload",
    FINGERPRINT_CAMERA: "/vehicle/fingerprint/camera",
    STORE: "/vehicle/store",
    LOOKUP: "/vehicle/lookup",
    VERIFY: "/vehicle/verify",
  },
  PIPELINE: {
    PROCESS_UPLOAD: "/pipeline/process/upload",
    PROCESS_CAMERA: "/pipeline/process/camera",
    STATUS: "/pipeline/status",
    METRICS: "/pipeline/metrics",
  },
  DECISION: {
    EVALUATE: "/decision/evaluate",
    STATISTICS: "/decision/statistics",
    HISTORY: "/decision/history",
  },
  IDENTITY: {
    VERIFY: "/identity/verify",
    SEARCH: "/identity/search",
    STATS: "/identity/stats",
    ACTIVITY: "/identity/activity",
    DRIVERS: {
      BASE: "/identity/drivers",
      BY_ID: (id: string) => `/identity/drivers/${id}`,
    },
    VEHICLES: {
      BASE: "/identity/vehicles",
      BY_ID: (id: string) => `/identity/vehicles/${id}`,
    },
    POLICIES: {
      BASE: "/identity/policies",
      BY_ID: (id: string) => `/identity/policies/${id}`,
    },
    LINK: "/identity/link",
    UNLINK: "/identity/unlink",
    ENROLLMENT: {
      DRIVER: "/identity/enroll/driver",
      VEHICLE: "/identity/enroll/vehicle",
    },
    RELATIONSHIPS: "/identity/relationships",
  },
  GATE: {
    ENTRY: "/gate/entry",
    EXIT: "/gate/exit",
    STATISTICS: "/gate/statistics",
    ACTIVE: "/gate/active",
    TRANSACTIONS: "/gate/transactions",
  },
  DASHBOARD: {
    METRICS: "/admin/dashboard",
    ANALYTICS: "/admin/analytics",
    REPORTS: "/admin/reports",
    EVENTS: "/admin/events",
  },
  ADMIN: {
    SEARCH: "/admin/search",
    EXPORT: "/admin/export",
    MANUAL_REVIEWS: "/admin/manual-reviews",
    APPROVE_REVIEW: (id: string) => `/admin/manual-review/${id}/approve`,
    REJECT_REVIEW: (id: string) => `/admin/manual-review/${id}/reject`,
    EVENTS: "/admin/events",
  },
  SYSTEM: {
    HEALTH: "/system/health",
    MODELS: "/system/models",
    DATABASE: "/system/health/database",
    STORAGE_HEALTH: "/system/health/storage",
    STORAGE_INFO: "/system/storage",
    PERFORMANCE: "/system/performance",
    CONFIGURATION: "/system/configuration",
    VERSION: "/system/version",
    LOG_STATISTICS: "/system/logs/statistics",
    CLEANUP: "/system/storage/cleanup",
    BACKUP: {
      EXPORT: "/system/backup/export",
      IMPORT: "/system/backup/import",
      LIST: "/system/backups",
    },
  },
} as const;
