export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
  },
  HEALTH: "/health",
  USERS: {
    BASE: "/users",
    PROFILE: "/users/me",
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  SEARCH: "/search",
  CAMERA: {
    START: "/camera/start",
    STOP: "/camera/stop",
    STATUS: "/camera/status",
    CAPTURE: "/camera/capture",
    DETECT: "/camera/detect",
  },
  PLATE_DETECTION: {
    DETECT_UPLOAD: "/plate-detection/detect/upload",
    DETECT_CAMERA: "/plate-detection/detect/camera",
    HISTORY: "/plate-detection/history",
  },
  PIPELINE: {
    PROCESS_UPLOAD: "/pipeline/process/upload",
    PROCESS_CAMERA: "/pipeline/process/camera",
    STATUS: "/pipeline/status",
    METRICS: "/pipeline/metrics",
    PENDING_CREATE: "/pipeline/pending",
    PENDING_GET: "/pipeline/pending",
    PENDING_COMPLETE: "/pipeline/pending/complete",
  },
  FACE: {
    ENROLL: "/face/enroll",
    RECOGNIZE_UPLOAD: "/face/recognize/upload",
    COMPARE: "/face/compare",
    HISTORY: "/face/history",
    MODEL_INFO: "/face/model-info",
    HEALTH: "/face/health",
  },
  GATE: {
    ENTRY: "/gate/entry",
    EXIT: "/gate/exit",
    STATISTICS: "/gate/statistics",
    ACTIVE: "/gate/active",
    TRANSACTIONS: "/gate/transactions",
    SESSION: (id: string) => `/gate/session/${id}`,
  },
  DASHBOARD: {
    METRICS: "/admin/dashboard",
    ANALYTICS: "/admin/analytics",
    REPORTS: "/admin/reports",
  },
  ADMIN: {
    MANUAL_REVIEWS: "/admin/manual-reviews",
    APPROVE_REVIEW: (id: string) => `/admin/manual-review/${id}/approve`,
    REJECT_REVIEW: (id: string) => `/admin/manual-review/${id}/reject`,
    EVENTS: "/admin/events",
  },
  SYSTEM: {
    HEALTH: "/system/health",
    MODELS: "/system/models",
    PERFORMANCE: "/system/performance",
    VERSION: "/system/version",
  },
} as const;
